name: CI

on:
  schedule:
    - cron: '8,52 0-8,10-16 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      # - name: creates output
      #   run:  sh ./build.sh # some command from your repository that creates
      #                       # output to "source-directory" ("output" in the example)
      - name: Pushes to another repository
        uses: 0xtoko/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'specialopsio'
          destination-repository-name: 'CommitEveryDay'
          user-email: toko@specialops.io
          target-branch: main
          commit-message: 'refactor'